<script setup lang="ts">
import type { FormError } from '@nuxt/ui'
import type {
  AdminOrderEditableFoodItem,
  AdminOrderFormData,
  AdminOrderFormUserSummary,
  AdminOrderInput,
  AdminOrderPlanEditorSlotState,
  AdminOrderSummary,
  DayOfWeek,
  DetailedDayMenu,
  DetailedFoodItem,
  DetailedMenuSlot,
  FoodCatalogItem,
  MenuSlotType,
  OrderPaymentStatus,
  OrderStatus,
  PlanSummary,
  PlanType,
  SlotKey,
  WeeklyMenuDetail
} from '~~/types/types'
import { orderInputSchema } from '~~/types/menuSchema'
import {
  ORDER_PAYMENT_STATUS_VALUES,
  ORDER_STATUS_VALUES
} from '~~/types/types'
import { formatWeekRange } from '~/utils/formatters'
import { DAY_LABELS } from '~/utils/heltifud'

type OrderPlanRowState = {
  key: string
  planId: string
  quantity: number | null
  notas: string
  slots: AdminOrderPlanEditorSlotState[]
  autoGeneratedSlotsSnapshot: string
}

type DeliveryAddressState = {
  etiqueta: string
  destinatario: string
  telefono: string
  linea1: string
  linea2: string
  colonia: string
  ciudad: string
  estado: string
  codigoPostal: string
  referencias: string
  makeDefault: boolean
}

type OrderFormState = {
  userId: string
  weeklyMenuId: string
  deliveryAddressChoice: string
  status: OrderStatus
  paymentStatus: OrderPaymentStatus
  currency: string
  descuento: number | null
  extras: number | null
  costoEnvio: number | null
  scheduledFor: string
  firstDeliveryAt: string
  secondDeliveryAt: string
  tagsText: string
  notas: string
  notasInternas: string
  planItems: OrderPlanRowState[]
  deliveryAddress: DeliveryAddressState
}

type PendingRegenerationAction
  = { kind: 'weekly-menu', nextMenuId: string }
    | { kind: 'plan-selection', nextPlanIds: string[] }
    | { kind: 'quantity-change', rowKey: string, nextQuantity: number | null }

type UnifiedEditorEntry = {
  row: OrderPlanRowState
  rowIndex: number
  plan: PlanSummary
  slot: AdminOrderPlanEditorSlotState
}

type UnifiedEditorDay = {
  key: string
  selectionIndex: number
  dayOfWeek: DayOfWeek
  menuDayOrder: number
  cycle: number
  entries: UnifiedEditorEntry[]
}

const VISIBLE_DAY_KEYS = ['LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES'] as const
const PLAN_TYPE_TO_SLOT_KEY: Record<PlanType, SlotKey> = {
  DESAYUNO: 'desayuno',
  COMIDA: 'comida',
  CENA: 'cena'
}
const SLOT_KEY_TO_MENU_SLOT_TYPE: Record<SlotKey, MenuSlotType> = {
  desayuno: 'DESAYUNO',
  comida: 'COMIDA',
  cena: 'CENA',
  snack1: 'SNACK1',
  snack2: 'SNACK2'
}
const DAY_ORDER_MAP = {
  LUNES: 1,
  MARTES: 2,
  MIERCOLES: 3,
  JUEVES: 4,
  VIERNES: 5,
  SABADO: 6,
  DOMINGO: 7
} as const
const PLAN_TYPE_ORDER: Record<PlanType, number> = {
  DESAYUNO: 1,
  COMIDA: 2,
  CENA: 3
}
const NO_WEEKLY_MENU_VALUE = '__no-weekly-menu__'

const props = withDefaults(defineProps<{
  formData: AdminOrderFormData
  formId?: string
  hideSubmit?: boolean
}>(), {
  formId: 'admin-order-form',
  hideSubmit: false
})

const emit = defineEmits<{
  'saved': [value: AdminOrderSummary]
  'dirty-change': [value: boolean]
  'validity-change': [value: boolean]
  'submit-state-change': [value: boolean]
}>()

const toast = useToast()
const { saveOrder } = useOrders()
const {
  data: catalogItemsData,
  status: catalogStatus
} = await useFetch<FoodCatalogItem[]>('/api/food-components', {
  default: () => []
})

const sectionCardUi = {
  root: 'overflow-hidden rounded-[28px] border border-default/70 ring-0 divide-y-0 bg-elevated/40 shadow-sm shadow-black/5 backdrop-blur-sm',
  body: 'space-y-6 p-6 sm:p-7'
}
const fieldUi = {
  label: 'font-semibold text-highlighted',
  description: 'text-sm leading-6 text-muted',
  error: 'mt-2'
}

function createEmptyPlanRow(): OrderPlanRowState {
  return {
    key: globalThis.crypto.randomUUID(),
    planId: '',
    quantity: 1,
    notas: '',
    slots: [],
    autoGeneratedSlotsSnapshot: '[]'
  }
}

function createEmptyDeliveryAddress(): DeliveryAddressState {
  return {
    etiqueta: '',
    destinatario: '',
    telefono: '',
    linea1: '',
    linea2: '',
    colonia: '',
    ciudad: '',
    estado: '',
    codigoPostal: '',
    referencias: '',
    makeDefault: false
  }
}

function createInitialState(): OrderFormState {
  return {
    userId: '',
    weeklyMenuId: props.formData.menus.find(menu => menu.isActive)?.id ?? '',
    deliveryAddressChoice: 'none',
    status: 'INGRESADO',
    paymentStatus: 'PENDIENTE',
    currency: 'MXN',
    descuento: null,
    extras: null,
    costoEnvio: null,
    scheduledFor: '',
    firstDeliveryAt: '',
    secondDeliveryAt: '',
    tagsText: '',
    notas: '',
    notasInternas: '',
    planItems: [],
    deliveryAddress: createEmptyDeliveryAddress()
  }
}

function createEmptyEditableFoodItem(): AdminOrderEditableFoodItem {
  return {
    sourceFoodComponentId: null,
    catalogItemId: null,
    nombre: '',
    descripcion: '',
    calorias: 0,
    imagen: '',
    tipo: ''
  }
}

function cloneEditableFoodItem(item?: DetailedFoodItem | AdminOrderEditableFoodItem | null): AdminOrderEditableFoodItem | null {
  if (!item) {
    return null
  }

  return {
    sourceFoodComponentId: item.sourceFoodComponentId ?? null,
    catalogItemId: item.catalogItemId ?? null,
    nombre: item.nombre,
    descripcion: item.descripcion,
    calorias: item.calorias,
    imagen: item.imagen,
    tipo: item.tipo
  }
}

function cloneEditableSlot(slot?: DetailedMenuSlot | AdminOrderPlanEditorSlotState['slot'] | null) {
  if (!slot) {
    return {
      platilloPrincipal: createEmptyEditableFoodItem(),
      guarnicion1: null,
      guarnicion2: null,
      contenedor: '',
      adicionales: []
    }
  }

  return {
    platilloPrincipal: cloneEditableFoodItem(slot.platilloPrincipal) ?? createEmptyEditableFoodItem(),
    guarnicion1: cloneEditableFoodItem(slot.guarnicion1),
    guarnicion2: cloneEditableFoodItem(slot.guarnicion2),
    contenedor: slot.contenedor ?? '',
    adicionales: slot.adicionales.map(item => cloneEditableFoodItem(item) ?? createEmptyEditableFoodItem())
  }
}

function serializePlanSlots(slots: AdminOrderPlanEditorSlotState[]) {
  return JSON.stringify(slots.map(slot => ({
    sourceWeeklyMenuId: slot.sourceWeeklyMenuId ?? null,
    sourceMenuDayId: slot.sourceMenuDayId ?? null,
    sourceDaySlotId: slot.sourceDaySlotId ?? null,
    selectionIndex: slot.selectionIndex,
    dayOfWeek: slot.dayOfWeek,
    menuDayOrder: slot.menuDayOrder,
    slotType: slot.slotType,
    slot: {
      platilloPrincipal: cloneEditableFoodItem(slot.slot.platilloPrincipal),
      guarnicion1: cloneEditableFoodItem(slot.slot.guarnicion1),
      guarnicion2: cloneEditableFoodItem(slot.slot.guarnicion2),
      contenedor: slot.slot.contenedor ?? '',
      adicionales: slot.slot.adicionales.map(item => cloneEditableFoodItem(item))
    }
  })))
}

const state = reactive<OrderFormState>(createInitialState())
const fieldErrors = reactive<Record<string, string>>({})
const initialSnapshot = ref('')
const isSubmitting = ref(false)
const hasTriedSubmit = ref(false)
const selectedMenuDetail = ref<WeeklyMenuDetail | null>(null)
const isMenuDetailLoading = ref(false)
const regenerationConfirmOpen = ref(false)
const pendingRegeneration = ref<PendingRegenerationAction | null>(null)

const catalogItems = computed(() => catalogItemsData.value ?? [])
const isCatalogLoading = computed(() =>
  catalogStatus.value === 'idle' || catalogStatus.value === 'pending'
)
const isEditorLoading = computed(() =>
  isCatalogLoading.value || isMenuDetailLoading.value
)

const usersById = computed(() =>
  new Map(props.formData.users.map(user => [user.id, user]))
)
const plansById = computed(() =>
  new Map(props.formData.plans.map(plan => [plan.id, plan]))
)
const menusById = computed(() =>
  new Map(props.formData.menus.map(menu => [menu.id, menu]))
)

const selectedUser = computed(() =>
  state.userId ? usersById.value.get(state.userId) ?? null : null
)
const selectedMenu = computed(() =>
  state.weeklyMenuId ? menusById.value.get(state.weeklyMenuId) ?? null : null
)
const selectedAddress = computed(() => {
  if (!selectedUser.value || state.deliveryAddressChoice === 'none' || state.deliveryAddressChoice === 'new') {
    return null
  }

  return selectedUser.value.addresses.find(address => address.id === state.deliveryAddressChoice) ?? null
})

const userOptions = computed(() =>
  props.formData.users.map(user => ({
    label: `${formatUserLabel(user)} · ${user.email}`,
    value: user.id
  }))
)

const menuOptions = computed(() => [
  { label: 'Sin menú vinculado todavía', value: NO_WEEKLY_MENU_VALUE },
  ...props.formData.menus.map(menu => ({
    label: `${menu.name}${menu.isActive ? ' · Activo' : ''}`,
    value: menu.id
  }))
])

const statusOptions = ORDER_STATUS_VALUES.map(value => ({
  label: formatOrderStatus(value),
  value
}))

const paymentStatusOptions = ORDER_PAYMENT_STATUS_VALUES.map(value => ({
  label: formatPaymentStatus(value),
  value
}))
const planSelectionOptions = computed(() =>
  props.formData.plans.map(plan => ({
    label: `${plan.nombre} · ${formatPlanType(plan.tipo)} · ${formatCurrency(plan.precio)}`,
    value: plan.id
  }))
)
const selectedPlanIds = computed(() =>
  state.planItems
    .map(item => item.planId)
    .filter(Boolean)
)

const addressChoiceOptions = computed(() => {
  const options = [{ label: 'Sin dirección ligada', value: 'none' }]

  if (selectedUser.value) {
    selectedUser.value.addresses.forEach((address) => {
      options.push({
        label: `${address.etiqueta || 'Dirección'}${address.isDefault ? ' · Predeterminada' : ''}`,
        value: address.id
      })
    })
  }

  options.push({ label: 'Capturar nueva dirección', value: 'new' })

  return options
})

const filledPlanRows = computed(() =>
  state.planItems.filter(item => item.planId && item.quantity && item.quantity > 0)
)

const editablePlanRows = computed(() =>
  state.planItems
    .map((item, index) => ({
      item,
      index,
      plan: item.planId ? plansById.value.get(item.planId) ?? null : null
    }))
    .filter(entry => Boolean(entry.plan && entry.item.quantity && entry.item.quantity > 0)) as Array<{
    item: OrderPlanRowState
    index: number
    plan: PlanSummary
  }>
)

const selectedPlansPreview = computed(() =>
  editablePlanRows.value.map(({ item, index, plan }) => ({
    index,
    key: item.key,
    item,
    plan,
    lineSubtotal: (plan.precio ?? 0) * Number(item.quantity ?? 0),
    requestedDishCount: plan.dishCount * Number(item.quantity ?? 0)
  }))
)

const subtotalPreview = computed(() =>
  selectedPlansPreview.value.reduce((sum, item) => sum + item.lineSubtotal, 0)
)
const requestedDishCountPreview = computed(() =>
  selectedPlansPreview.value.reduce((sum, item) => sum + item.requestedDishCount, 0)
)
const bagCountPreview = computed(() =>
  selectedPlansPreview.value.reduce((sum, item) => sum + Number(item.item.quantity ?? 0), 0)
)
const totalPreview = computed(() =>
  Math.max(
    0,
    subtotalPreview.value - (state.descuento ?? 0) + (state.extras ?? 0) + (state.costoEnvio ?? 0)
  )
)
const hasAnyFormData = computed(() =>
  props.formData.users.length > 0 && props.formData.plans.length > 0
)
const unifiedEditorDays = computed<UnifiedEditorDay[]>(() => {
  const maxSelectionCount = editablePlanRows.value.reduce(
    (maxCount, entry) => Math.max(maxCount, entry.item.slots.length),
    0
  )

  return Array.from({ length: maxSelectionCount }, (_, index) => {
    const entries = editablePlanRows.value
      .map((entry) => {
        const slot = entry.item.slots[index]

        if (!slot) {
          return null
        }

        return {
          row: entry.item,
          rowIndex: entry.index,
          plan: entry.plan,
          slot
        } satisfies UnifiedEditorEntry
      })
      .filter(Boolean)
      .sort((left, right) => {
        const leftEntry = left as UnifiedEditorEntry
        const rightEntry = right as UnifiedEditorEntry
        const byPlanType = PLAN_TYPE_ORDER[leftEntry.plan.tipo] - PLAN_TYPE_ORDER[rightEntry.plan.tipo]

        if (byPlanType !== 0) {
          return byPlanType
        }

        return leftEntry.rowIndex - rightEntry.rowIndex
      }) as UnifiedEditorEntry[]

    const referenceSlot = entries[0]?.slot

    return {
      key: `editor-day-${index + 1}`,
      selectionIndex: index + 1,
      dayOfWeek: referenceSlot?.dayOfWeek ?? 'LUNES',
      menuDayOrder: referenceSlot?.menuDayOrder ?? index + 1,
      cycle: Math.ceil((index + 1) / VISIBLE_DAY_KEYS.length),
      entries
    }
  })
})

const openUnifiedDayKeys = ref<number[]>([])

function rowHasManualSlotEdits(row: OrderPlanRowState) {
  return row.slots.length > 0 && serializePlanSlots(row.slots) !== row.autoGeneratedSlotsSnapshot
}

function isUnifiedDayOpen(selectionIndex: number) {
  return openUnifiedDayKeys.value.includes(selectionIndex)
}

function toggleUnifiedDay(selectionIndex: number) {
  openUnifiedDayKeys.value = isUnifiedDayOpen(selectionIndex)
    ? openUnifiedDayKeys.value.filter(value => value !== selectionIndex)
    : [...openUnifiedDayKeys.value, selectionIndex]
}

function getUnifiedDayLabel(day: UnifiedEditorDay) {
  if (day.cycle <= 1) {
    return DAY_LABELS[day.dayOfWeek]
  }

  return `${DAY_LABELS[day.dayOfWeek]} · vuelta ${day.cycle}`
}

function countCompletedEntries(day: UnifiedEditorDay) {
  return day.entries.reduce((count, entry) => {
    const isComplete = Boolean(
      entry.slot.slot.platilloPrincipal.catalogItemId
      && entry.slot.slot.contenedor?.trim()
    )

    return count + (isComplete ? 1 : 0)
  }, 0)
}

function serializeFormState() {
  return JSON.stringify({
    userId: state.userId,
    weeklyMenuId: state.weeklyMenuId,
    deliveryAddressChoice: state.deliveryAddressChoice,
    status: state.status,
    paymentStatus: state.paymentStatus,
    currency: state.currency.trim().toUpperCase(),
    descuento: state.descuento,
    extras: state.extras,
    costoEnvio: state.costoEnvio,
    scheduledFor: state.scheduledFor,
    firstDeliveryAt: state.firstDeliveryAt,
    secondDeliveryAt: state.secondDeliveryAt,
    tagsText: state.tagsText,
    notas: state.notas,
    notasInternas: state.notasInternas,
    planItems: state.planItems.map(item => ({
      planId: item.planId,
      quantity: item.quantity,
      notas: item.notas,
      slots: serializePlanSlots(item.slots)
    })),
    deliveryAddress: {
      ...state.deliveryAddress
    }
  })
}

function toPayloadFoodItem(item?: AdminOrderEditableFoodItem | null) {
  if (!item) {
    return null
  }

  return {
    sourceFoodComponentId: item.sourceFoodComponentId ?? null,
    catalogItemId: item.catalogItemId ?? null,
    nombre: item.nombre.trim(),
    descripcion: item.descripcion.trim(),
    calorias: Number(item.calorias ?? 0),
    imagen: item.imagen.trim(),
    tipo: item.tipo.trim()
  }
}

function isPresentFoodItem(
  item: ReturnType<typeof toPayloadFoodItem>
): item is NonNullable<ReturnType<typeof toPayloadFoodItem>> {
  return Boolean(item)
}

const orderPayload = computed<AdminOrderInput>(() => ({
  userId: state.userId,
  weeklyMenuId: state.weeklyMenuId || null,
  deliveryAddressId: state.deliveryAddressChoice !== 'none' && state.deliveryAddressChoice !== 'new'
    ? state.deliveryAddressChoice
    : null,
  deliveryAddress: state.deliveryAddressChoice === 'new'
    ? {
        etiqueta: state.deliveryAddress.etiqueta.trim(),
        destinatario: state.deliveryAddress.destinatario.trim(),
        telefono: state.deliveryAddress.telefono.trim(),
        linea1: state.deliveryAddress.linea1.trim(),
        linea2: state.deliveryAddress.linea2.trim(),
        colonia: state.deliveryAddress.colonia.trim(),
        ciudad: state.deliveryAddress.ciudad.trim(),
        estado: state.deliveryAddress.estado.trim(),
        codigoPostal: state.deliveryAddress.codigoPostal.trim(),
        pais: 'MX',
        referencias: state.deliveryAddress.referencias.trim(),
        makeDefault: state.deliveryAddress.makeDefault
      }
    : null,
  status: state.status,
  paymentStatus: state.paymentStatus,
  currency: state.currency.trim().toUpperCase(),
  descuento: state.descuento,
  extras: state.extras,
  costoEnvio: state.costoEnvio,
  scheduledFor: state.scheduledFor || null,
  firstDeliveryAt: state.firstDeliveryAt || null,
  secondDeliveryAt: state.secondDeliveryAt || null,
  tags: state.tagsText
    .split(',')
    .map(tag => tag.trim())
    .filter(Boolean),
  notas: state.notas.trim(),
  notasInternas: state.notasInternas.trim(),
  planItems: editablePlanRows.value.map(({ item }) => ({
    planId: item.planId,
    quantity: Number(item.quantity ?? 0),
    notas: item.notas.trim(),
    slots: item.slots.map(slot => ({
      sourceWeeklyMenuId: slot.sourceWeeklyMenuId ?? null,
      sourceMenuDayId: slot.sourceMenuDayId ?? null,
      sourceDaySlotId: slot.sourceDaySlotId ?? null,
      selectionIndex: slot.selectionIndex,
      dayOfWeek: slot.dayOfWeek,
      menuDayOrder: slot.menuDayOrder,
      slotType: slot.slotType,
      contenedor: (slot.slot.contenedor ?? '').trim(),
      platilloPrincipal: toPayloadFoodItem(slot.slot.platilloPrincipal) ?? createEmptyEditableFoodItem(),
      guarnicion1: toPayloadFoodItem(slot.slot.guarnicion1),
      guarnicion2: toPayloadFoodItem(slot.slot.guarnicion2),
      adicionales: slot.slot.adicionales
        .map(itemDetail => toPayloadFoodItem(itemDetail))
        .filter(isPresentFoodItem)
    }))
  }))
}))

const validationResult = computed(() => orderInputSchema.safeParse(orderPayload.value))
const canSubmit = computed(() => validationResult.value.success)
const hasUnsavedChanges = computed(() => serializeFormState() !== initialSnapshot.value)

const formErrors = computed<FormError[]>(() =>
  Object.entries(fieldErrors)
    .filter(([, message]) => Boolean(message))
    .map(([name, message]) => ({ name, message }))
)

const slotFieldErrors = computed(() => {
  const errors: Record<string, string> = {}

  if (validationResult.value.success) {
    return errors
  }

  validationResult.value.error.issues.forEach((issue) => {
    const [planKey, planIndex, slotsKey, slotIndex, fieldKey] = issue.path

    if (
      planKey !== 'planItems'
      || slotsKey !== 'slots'
      || typeof planIndex !== 'number'
      || typeof slotIndex !== 'number'
      || typeof fieldKey !== 'string'
    ) {
      return
    }

    errors[`${planIndex}.${slotIndex}.${fieldKey}`] = issue.message
  })

  return errors
})

const confirmRegenerationTitle = computed(() =>
  pendingRegeneration.value?.kind === 'weekly-menu'
    ? 'Cambiar menú base'
    : 'Regenerar selección del plan'
)

const confirmRegenerationDescription = computed(() => {
  if (!pendingRegeneration.value) {
    return ''
  }

  if (pendingRegeneration.value.kind === 'weekly-menu') {
    return 'Ya hiciste cambios manuales en uno o más planes. Si cambias el menú semanal se volverán a llenar todos los días desde el nuevo menú base y se perderán esos ajustes.'
  }

  return 'Este plan ya tiene cambios manuales. Si continúas, se reconstruirá día por día usando los defaults del menú semanal y se perderán los cambios hechos en ese editor.'
})

function clearFieldErrors() {
  Object.keys(fieldErrors).forEach((key) => {
    fieldErrors[key] = ''
  })
}

function resetDeliveryAddress() {
  Object.assign(state.deliveryAddress, createEmptyDeliveryAddress())
}

function prefillDeliveryAddressFromUser(user: AdminOrderFormUserSummary) {
  state.deliveryAddress.destinatario = state.deliveryAddress.destinatario || formatUserLabel(user)
  state.deliveryAddress.telefono = state.deliveryAddress.telefono || user.telefono || ''
  state.deliveryAddress.linea1 = state.deliveryAddress.linea1 || user.primaryAddress || ''
  state.deliveryAddress.linea2 = state.deliveryAddress.linea2 || user.primaryAddress2 || ''
}

function syncAddressChoiceForUser(user: AdminOrderFormUserSummary | null) {
  if (!user) {
    state.deliveryAddressChoice = 'none'
    resetDeliveryAddress()
    return
  }

  const existingChoiceBelongsToUser = user.addresses.some(address => address.id === state.deliveryAddressChoice)

  if (state.deliveryAddressChoice === 'new') {
    prefillDeliveryAddressFromUser(user)
    return
  }

  if (existingChoiceBelongsToUser) {
    return
  }

  if (user.addresses.length > 0) {
    state.deliveryAddressChoice = user.addresses.find(address => address.isDefault)?.id ?? user.addresses[0]!.id
    resetDeliveryAddress()
    return
  }

  state.deliveryAddressChoice = 'new'
  prefillDeliveryAddressFromUser(user)
}

function formatUserLabel(user: Pick<AdminOrderFormUserSummary, 'nombre' | 'apellidos' | 'email'>) {
  const fullName = `${user.nombre} ${user.apellidos}`.trim()
  return fullName || user.email
}

function formatOrderStatus(value: OrderStatus) {
  return {
    BORRADOR: 'Borrador',
    INGRESADO: 'Ingresado',
    CONFIRMADO: 'Confirmado',
    PAGADO: 'Pagado',
    EMPACADO: 'Empacado',
    EMPACADO_POR_PAGAR: 'Empacado por pagar',
    PROGRAMADO: 'Programado',
    EN_RUTA: 'En ruta',
    ENTREGADO: 'Entregado',
    ENTREGADO_POR_PAGAR: 'Entregado por pagar',
    COMPLETADO: 'Completado',
    COMPLETADO_POR_PAGAR: 'Completado por pagar',
    CANCELADO: 'Cancelado'
  }[value]
}

function formatPaymentStatus(value: OrderPaymentStatus) {
  return {
    PENDIENTE: 'Pendiente',
    PAGADO: 'Pagado',
    FALLIDO: 'Fallido',
    REEMBOLSADO: 'Reembolsado'
  }[value]
}

function formatPlanType(value: PlanType) {
  return {
    DESAYUNO: 'Desayuno',
    COMIDA: 'Comida',
    CENA: 'Cena'
  }[value]
}

function formatCurrency(value: number | null, currency = 'MXN', fallback = 'Sin monto') {
  if (value === null) {
    return fallback
  }

  return new Intl.NumberFormat('es-MX', {
    style: 'currency',
    currency,
    maximumFractionDigits: 2
  }).format(value)
}

function getRequestedDishCount(row: OrderPlanRowState, plan?: PlanSummary | null) {
  if (!plan || !row.quantity || row.quantity <= 0) {
    return 0
  }

  return plan.dishCount * Number(row.quantity)
}

function setRowSlots(row: OrderPlanRowState, slots: AdminOrderPlanEditorSlotState[]) {
  row.slots = slots
  row.autoGeneratedSlotsSnapshot = serializePlanSlots(slots)
}

function clearRowSlots(row: OrderPlanRowState) {
  setRowSlots(row, [])
}

function getVisibleMenuDays(menu: WeeklyMenuDetail) {
  return VISIBLE_DAY_KEYS
    .map(dayOfWeek => menu.days.find(day => day.dayOfWeek === dayOfWeek))
    .filter(Boolean) as DetailedDayMenu[]
}

function buildDefaultSlotsForPlan(plan: PlanSummary, row: OrderPlanRowState, menu: WeeklyMenuDetail) {
  const requestedDishCount = getRequestedDishCount(row, plan)

  if (requestedDishCount <= 0) {
    return []
  }

  const slotKey = PLAN_TYPE_TO_SLOT_KEY[plan.tipo]
  const slotType = SLOT_KEY_TO_MENU_SLOT_TYPE[slotKey]
  const templates = getVisibleMenuDays(menu).map((day) => {
    const sourceSlot = day[slotKey]

    return {
      sourceWeeklyMenuId: menu.id,
      sourceMenuDayId: day.sourceMenuDayId ?? null,
      sourceDaySlotId: sourceSlot.sourceDaySlotId ?? null,
      dayOfWeek: day.dayOfWeek,
      menuDayOrder: day.menuDayOrder ?? DAY_ORDER_MAP[day.dayOfWeek],
      slotType,
      slot: cloneEditableSlot(sourceSlot)
    }
  })

  if (!templates.length) {
    return []
  }

  return Array.from({ length: requestedDishCount }, (_, index) => {
    const template = templates[index % templates.length]!

    return {
      sourceWeeklyMenuId: template.sourceWeeklyMenuId,
      sourceMenuDayId: template.sourceMenuDayId,
      sourceDaySlotId: template.sourceDaySlotId,
      selectionIndex: index + 1,
      dayOfWeek: template.dayOfWeek,
      menuDayOrder: template.menuDayOrder,
      slotType: template.slotType,
      slot: cloneEditableSlot(template.slot)
    } satisfies AdminOrderPlanEditorSlotState
  })
}

function syncRowEditorFromCurrentMenu(row: OrderPlanRowState) {
  const plan = row.planId ? plansById.value.get(row.planId) ?? null : null

  if (!selectedMenuDetail.value || !plan || !row.quantity || row.quantity <= 0) {
    clearRowSlots(row)
    return
  }

  setRowSlots(row, buildDefaultSlotsForPlan(plan, row, selectedMenuDetail.value))
}

function syncAllPlanEditorsFromCurrentMenu() {
  state.planItems.forEach(row => syncRowEditorFromCurrentMenu(row))
}

async function syncSelectedMenuDetail(menuId: string) {
  if (!menuId) {
    selectedMenuDetail.value = null
    return
  }

  isMenuDetailLoading.value = true

  try {
    selectedMenuDetail.value = await $fetch<WeeklyMenuDetail>(`/api/menu/${menuId}`)
  } catch (error) {
    selectedMenuDetail.value = null

    if (import.meta.client) {
      toast.add({
        title: 'No pudimos cargar el menú seleccionado',
        description: error instanceof Error ? error.message : 'Intenta de nuevo en unos segundos.',
        color: 'error',
        icon: 'i-lucide-circle-alert'
      })
    }
  } finally {
    isMenuDetailLoading.value = false
  }
}

async function applyWeeklyMenuChange(nextMenuId: string) {
  state.weeklyMenuId = nextMenuId
  await syncSelectedMenuDetail(nextMenuId)
  syncAllPlanEditorsFromCurrentMenu()
}

async function handleWeeklyMenuChange(value: string | number | undefined) {
  const rawValue = typeof value === 'string' ? value : ''
  const nextMenuId = rawValue === NO_WEEKLY_MENU_VALUE ? '' : rawValue

  if (nextMenuId === state.weeklyMenuId) {
    return
  }

  if (state.planItems.some(row => rowHasManualSlotEdits(row))) {
    pendingRegeneration.value = {
      kind: 'weekly-menu',
      nextMenuId
    }
    regenerationConfirmOpen.value = true
    return
  }

  await applyWeeklyMenuChange(nextMenuId)
}

function buildPlanRowsFromSelection(nextPlanIds: string[]) {
  const currentRowsByPlanId = new Map(
    state.planItems
      .filter(item => item.planId)
      .map(item => [item.planId, item])
  )

  state.planItems = nextPlanIds.map((planId) => {
    const existing = currentRowsByPlanId.get(planId)

    if (existing) {
      return existing
    }

    const newRow = createEmptyPlanRow()
    newRow.planId = planId
    syncRowEditorFromCurrentMenu(newRow)
    return newRow
  })
}

function handlePlanSelectionChange(value: string[] | undefined) {
  const nextPlanIds = (value ?? []).filter(Boolean)
  const removingEditedPlan = state.planItems.some(item =>
    item.planId
    && !nextPlanIds.includes(item.planId)
    && rowHasManualSlotEdits(item)
  )

  if (removingEditedPlan) {
    pendingRegeneration.value = {
      kind: 'plan-selection',
      nextPlanIds
    }
    regenerationConfirmOpen.value = true
    return
  }

  buildPlanRowsFromSelection(nextPlanIds)
}

function applyQuantityChange(row: OrderPlanRowState, nextQuantity: number | null) {
  row.quantity = nextQuantity
  syncRowEditorFromCurrentMenu(row)
}

function handleQuantityChange(row: OrderPlanRowState, value: number | undefined) {
  const nextQuantity = value === undefined ? null : Number(value)

  if (nextQuantity === row.quantity) {
    return
  }

  if (selectedMenuDetail.value && rowHasManualSlotEdits(row)) {
    pendingRegeneration.value = {
      kind: 'quantity-change',
      rowKey: row.key,
      nextQuantity
    }
    regenerationConfirmOpen.value = true
    return
  }

  applyQuantityChange(row, nextQuantity)
}

async function confirmRegeneration() {
  const action = pendingRegeneration.value

  if (!action) {
    return
  }

  regenerationConfirmOpen.value = false
  pendingRegeneration.value = null

  if (action.kind === 'weekly-menu') {
    await applyWeeklyMenuChange(action.nextMenuId)
    return
  }

  if (action.kind === 'plan-selection') {
    buildPlanRowsFromSelection(action.nextPlanIds)
    return
  }

  const row = state.planItems.find(item => item.key === action.rowKey)

  if (!row) {
    return
  }

  applyQuantityChange(row, action.nextQuantity)
}

function cancelRegeneration() {
  regenerationConfirmOpen.value = false
  pendingRegeneration.value = null
}

function removePlanRow(index: number) {
  const nextPlanIds = state.planItems
    .filter((_, itemIndex) => itemIndex !== index)
    .map(item => item.planId)
    .filter(Boolean)

  handlePlanSelectionChange(nextPlanIds)
}

function getPlanSlotError(rowIndex: number, selectionIndex: number, field: 'platilloPrincipal' | 'contenedor') {
  if (!hasTriedSubmit.value) {
    return undefined
  }

  const row = state.planItems[rowIndex]

  if (!row) {
    return undefined
  }

  const slotIndex = row.slots.findIndex(slot => slot.selectionIndex === selectionIndex)

  if (slotIndex < 0) {
    return undefined
  }

  return slotFieldErrors.value[`${rowIndex}.${slotIndex}.${field}`]
}

async function onSubmit() {
  if (isSubmitting.value || !hasAnyFormData.value) {
    return
  }

  clearFieldErrors()
  hasTriedSubmit.value = true

  if (!validationResult.value.success) {
    validationResult.value.error.issues.forEach((issue) => {
      const name = issue.path.join('.')

      if (!name || fieldErrors[name]) {
        return
      }

      fieldErrors[name] = issue.message
    })

    toast.add({
      title: 'El pedido no se pudo guardar',
      description: 'Revisa los campos obligatorios antes de continuar.',
      color: 'error',
      icon: 'i-lucide-circle-alert'
    })
    return
  }

  isSubmitting.value = true

  try {
    const saved = await saveOrder(orderPayload.value)
    initialSnapshot.value = serializeFormState()
    toast.add({
      title: 'Pedido creado',
      color: 'success',
      icon: 'i-lucide-check-circle'
    })
    emit('saved', saved)
  } catch (error) {
    toast.add({
      title: 'No pudimos guardar el pedido',
      description: error instanceof Error ? error.message : 'Intenta de nuevo en unos segundos.',
      color: 'error',
      icon: 'i-lucide-circle-alert'
    })
  } finally {
    isSubmitting.value = false
  }
}

watch(() => state.userId, () => {
  resetDeliveryAddress()
  syncAddressChoiceForUser(selectedUser.value)
})

watch(() => state.deliveryAddressChoice, (value) => {
  if (value === 'new' && selectedUser.value) {
    prefillDeliveryAddressFromUser(selectedUser.value)
  }

  if (value !== 'new') {
    resetDeliveryAddress()
  }
})

watch(
  () => unifiedEditorDays.value.map(day => day.selectionIndex),
  (selectionIndexes) => {
    if (!selectionIndexes.length) {
      openUnifiedDayKeys.value = []
      return
    }

    openUnifiedDayKeys.value = openUnifiedDayKeys.value.filter(value =>
      selectionIndexes.includes(value)
    )

    if (!openUnifiedDayKeys.value.length) {
      openUnifiedDayKeys.value = [selectionIndexes[0]!]
    }
  },
  { immediate: true }
)

watch(hasUnsavedChanges, value => emit('dirty-change', value), { immediate: true })
watch(canSubmit, value => emit('validity-change', value), { immediate: true })
watch(isSubmitting, value => emit('submit-state-change', value), { immediate: true })

await syncSelectedMenuDetail(state.weeklyMenuId)
initialSnapshot.value = serializeFormState()
</script>

<template>
  <UForm
    :id="formId"
    :state="state"
    :errors="formErrors"
    class="space-y-6"
    @submit.prevent="onSubmit"
  >
    <UCard :ui="sectionCardUi">
      <div class="space-y-2">
        <p class="text-xs font-semibold uppercase tracking-[0.18em] text-primary/80">
          Contexto comercial
        </p>
        <h2 class="text-xl font-semibold text-primary">
          Cliente y estatus base
        </h2>
        <p class="text-sm leading-6 text-muted">
          Arranca definiendo para quién es el pedido y en qué momento del pipeline entra.
        </p>
      </div>

      <div class="grid gap-4 xl:grid-cols-[minmax(0,1.3fr)_minmax(0,0.8fr)_minmax(0,0.8fr)]">
        <UFormField
          name="userId"
          label="Cliente"
          description="Selecciona el usuario que recibirá el pedido."
          :ui="fieldUi"
        >
          <USelect
            v-model="state.userId"
            :items="userOptions"
            class="w-full"
            size="xl"
            placeholder="Selecciona un cliente"
          />
        </UFormField>

        <UFormField
          name="status"
          label="Estado del pedido"
          description="Marca la etapa operativa inicial."
          :ui="fieldUi"
        >
          <USelect
            v-model="state.status"
            :items="statusOptions"
            class="w-full"
            size="xl"
          />
        </UFormField>

        <UFormField
          name="paymentStatus"
          label="Estado de cobro"
          description="Se usará para seguimiento financiero."
          :ui="fieldUi"
        >
          <USelect
            v-model="state.paymentStatus"
            :items="paymentStatusOptions"
            class="w-full"
            size="xl"
          />
        </UFormField>
      </div>

      <div
        v-if="selectedUser"
        class="grid gap-4 rounded-2xl border border-default/60 bg-default/25 p-4 sm:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)] sm:p-5"
      >
        <div class="space-y-1">
          <p class="text-sm font-medium text-highlighted">
            {{ formatUserLabel(selectedUser) }}
          </p>
          <p class="text-sm text-muted">
            {{ selectedUser.email }}
          </p>
          <p class="text-xs text-muted">
            {{ selectedUser.telefono || 'Sin teléfono registrado' }}
          </p>
        </div>

        <div class="space-y-1">
          <p class="text-xs font-semibold uppercase tracking-[0.16em] text-muted">
            Contexto rápido
          </p>
          <p class="text-sm text-muted">
            {{ selectedUser.primaryAddress || 'Sin referencia principal' }}
          </p>
          <p v-if="selectedUser.primaryAddress2" class="text-xs text-muted">
            {{ selectedUser.primaryAddress2 }}
          </p>
        </div>
      </div>
    </UCard>

    <UCard :ui="sectionCardUi">
      <div class="space-y-2">
        <p class="text-xs font-semibold uppercase tracking-[0.18em] text-primary/80">
          Menú y entrega
        </p>
        <h2 class="text-xl font-semibold text-primary">
          Snapshot operativo
        </h2>
        <p class="text-sm leading-6 text-muted">
          Vincula el pedido a un menú semanal, define entregas y después ajusta el menú del cliente plan por plan.
        </p>
      </div>

      <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_repeat(3,minmax(0,0.8fr))]">
        <UFormField
          name="weeklyMenuId"
          label="Menú semanal"
          description="Si seleccionas uno, cada plan se llenará por default con sus días correspondientes."
          :ui="fieldUi"
        >
          <USelect
            :model-value="state.weeklyMenuId || NO_WEEKLY_MENU_VALUE"
            :items="menuOptions"
            class="w-full"
            size="xl"
            @update:model-value="handleWeeklyMenuChange"
          />
        </UFormField>

        <UFormField
          name="scheduledFor"
          label="Programado para"
          description="Fecha general comprometida."
          :ui="fieldUi"
        >
          <UInput
            v-model="state.scheduledFor"
            type="datetime-local"
            class="w-full"
            size="xl"
          />
        </UFormField>

        <UFormField
          name="firstDeliveryAt"
          label="Primera entrega"
          description="Úsalo si se parte la entrega."
          :ui="fieldUi"
        >
          <UInput
            v-model="state.firstDeliveryAt"
            type="datetime-local"
            class="w-full"
            size="xl"
          />
        </UFormField>

        <UFormField
          name="secondDeliveryAt"
          label="Segunda entrega"
          description="Opcional para reenvíos o doble visita."
          :ui="fieldUi"
        >
          <UInput
            v-model="state.secondDeliveryAt"
            type="datetime-local"
            class="w-full"
            size="xl"
          />
        </UFormField>
      </div>

      <div
        v-if="selectedMenu"
        class="rounded-2xl border border-default/60 bg-default/25 p-4 sm:p-5"
      >
        <p class="text-sm font-medium text-highlighted">
          {{ selectedMenu.name }}
        </p>
        <p class="mt-1 text-sm text-muted">
          {{ formatWeekRange(selectedMenu.startDate, selectedMenu.endDate) }}
        </p>
      </div>

      <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,1.2fr)]">
        <UFormField
          name="deliveryAddressId"
          label="Dirección de entrega"
          description="Puedes reutilizar una existente o capturar una nueva."
          :ui="fieldUi"
        >
          <USelect
            v-model="state.deliveryAddressChoice"
            :items="addressChoiceOptions"
            class="w-full"
            size="xl"
          />
        </UFormField>

        <div class="rounded-2xl border border-default/60 bg-default/25 p-4 sm:p-5">
          <p class="text-xs font-semibold uppercase tracking-[0.16em] text-muted">
            Estado actual
          </p>
          <p class="mt-2 text-sm text-muted">
            <template v-if="selectedAddress">
              {{ selectedAddress.summary }}
            </template>
            <template v-else-if="state.deliveryAddressChoice === 'new'">
              Se creará una nueva dirección y quedará ligada al cliente.
            </template>
            <template v-else>
              El pedido quedará sin dirección ligada por ahora.
            </template>
          </p>
        </div>
      </div>

      <div
        v-if="state.deliveryAddressChoice === 'new'"
        class="space-y-4 rounded-2xl border border-default/60 bg-default/25 p-4 sm:p-5"
      >
        <div class="grid gap-4 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,1fr)_minmax(0,0.8fr)]">
          <UFormField
            name="deliveryAddress.etiqueta"
            label="Etiqueta"
            description="Ej. Casa, oficina o punto de entrega."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.etiqueta"
              class="w-full"
              size="xl"
              placeholder="Casa"
            />
          </UFormField>

          <UFormField
            name="deliveryAddress.destinatario"
            label="Destinatario"
            description="Nombre visible para la entrega."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.destinatario"
              class="w-full"
              size="xl"
              placeholder="Nombre de quien recibe"
            />
          </UFormField>

          <UFormField
            name="deliveryAddress.telefono"
            label="Teléfono"
            description="Contacto directo en ruta."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.telefono"
              class="w-full"
              size="xl"
              placeholder="664 123 4567"
            />
          </UFormField>
        </div>

        <div class="grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)]">
          <UFormField
            name="deliveryAddress.linea1"
            label="Línea principal"
            description="Calle, número o punto principal."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.linea1"
              class="w-full"
              size="xl"
              placeholder="Calle, número y colonia principal"
            />
          </UFormField>

          <UFormField
            name="deliveryAddress.linea2"
            label="Complemento"
            description="Departamento, acceso o referencias cortas."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.linea2"
              class="w-full"
              size="xl"
              placeholder="Depto, acceso o referencia"
            />
          </UFormField>
        </div>

        <div class="grid gap-4 xl:grid-cols-[minmax(0,0.8fr)_minmax(0,0.8fr)_minmax(0,0.8fr)_minmax(0,0.6fr)]">
          <UFormField
            name="deliveryAddress.colonia"
            label="Colonia"
            description="Dato opcional para la ruta."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.colonia"
              class="w-full"
              size="xl"
              placeholder="Colonia"
            />
          </UFormField>

          <UFormField
            name="deliveryAddress.ciudad"
            label="Ciudad"
            description="Campo obligatorio."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.ciudad"
              class="w-full"
              size="xl"
              placeholder="Tijuana"
            />
          </UFormField>

          <UFormField
            name="deliveryAddress.estado"
            label="Estado"
            description="Campo obligatorio."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.estado"
              class="w-full"
              size="xl"
              placeholder="Baja California"
            />
          </UFormField>

          <UFormField
            name="deliveryAddress.codigoPostal"
            label="CP"
            description="Opcional."
            :ui="fieldUi"
          >
            <UInput
              v-model="state.deliveryAddress.codigoPostal"
              class="w-full"
              size="xl"
              placeholder="22000"
            />
          </UFormField>
        </div>

        <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,0.8fr)]">
          <UFormField
            name="deliveryAddress.referencias"
            label="Referencias"
            description="Indicaciones útiles para repartidor o empaque."
            :ui="fieldUi"
          >
            <UTextarea
              v-model="state.deliveryAddress.referencias"
              class="w-full"
              :rows="3"
              autoresize
              placeholder="Portón blanco, tocar timbre, entregar en recepción..."
            />
          </UFormField>

          <div class="rounded-2xl border border-default/60 bg-elevated/40 p-4 sm:p-5">
            <UFormField
              name="deliveryAddress.makeDefault"
              label="Guardar como predeterminada"
              description="Úsalo si esta dirección será la principal del cliente."
              :ui="fieldUi"
            >
              <div class="flex items-center justify-between gap-4 rounded-2xl border border-default/60 bg-default/70 px-4 py-3">
                <div class="space-y-1">
                  <p class="text-sm font-medium text-highlighted">
                    {{ state.deliveryAddress.makeDefault ? 'Sí, usar como principal' : 'Sólo para este pedido' }}
                  </p>
                  <p class="text-xs text-muted">
                    La dirección se guardará en el perfil del cliente.
                  </p>
                </div>

                <USwitch v-model="state.deliveryAddress.makeDefault" />
              </div>
            </UFormField>
          </div>
        </div>
      </div>

      <div class="space-y-4">
        <div class="space-y-2">
          <p class="text-xs font-semibold uppercase tracking-[0.18em] text-primary/80">
            Editor del cliente
          </p>
          <h3 class="text-lg font-semibold text-primary">
            Selección día por día
          </h3>
          <p class="text-sm leading-6 text-muted">
            El editor replica la estructura de creación de menú, pero sólo muestra tarjetas para los planes agregados en el pedido y en el orden correspondiente.
          </p>
        </div>

        <UAlert
          v-if="isMenuDetailLoading"
          title="Cargando menú base"
          description="Estamos trayendo el menú semanal detallado para poder llenar los planes."
          color="neutral"
          variant="soft"
          icon="i-lucide-loader-circle"
        />

        <UAlert
          v-else-if="!state.weeklyMenuId"
          title="Sin menú vinculado todavía"
          description="Puedes guardar el pedido sin resolver platillos, o seleccionar un menú semanal para editar cada plan día por día."
          color="neutral"
          variant="soft"
          icon="i-lucide-clipboard-minus"
        />

        <UAlert
          v-else-if="!editablePlanRows.length"
          title="Agrega al menos un plan para abrir el editor"
          description="En cuanto captures uno o más planes con cantidad, activaremos únicamente sus tarjetas dentro del editor."
          color="neutral"
          variant="soft"
          icon="i-lucide-package-open"
        />

        <UAlert
          v-else-if="!selectedMenuDetail"
          title="No pudimos hidratar el menú"
          description="El pedido aún se puede guardar, pero quedará sin resolución de platillos hasta que el menú base vuelva a cargarse."
          color="warning"
          variant="soft"
          icon="i-lucide-circle-alert"
        />

        <div v-else class="space-y-5">
          <div class="flex flex-wrap items-center gap-2">
            <UBadge
              v-for="editor in editablePlanRows"
              :key="`${editor.item.key}-editor-badge`"
              color="primary"
              variant="subtle"
            >
              {{ editor.plan.nombre }} · {{ getRequestedDishCount(editor.item, editor.plan) }} {{ getRequestedDishCount(editor.item, editor.plan) === 1 ? 'día' : 'días' }}
            </UBadge>
          </div>

          <section
            v-for="day in unifiedEditorDays"
            :key="day.key"
            class="overflow-hidden rounded-2xl border border-default/70 bg-elevated/35 shadow-sm shadow-black/5"
          >
            <button
              type="button"
              class="flex w-full cursor-pointer items-center justify-between gap-3 border-b border-default/70 px-5 py-4 text-left"
              @click="toggleUnifiedDay(day.selectionIndex)"
            >
              <div class="space-y-1">
                <div class="flex flex-wrap items-center gap-2">
                  <UBadge color="primary" variant="soft">
                    Día {{ day.selectionIndex }}
                  </UBadge>
                  <UBadge color="neutral" variant="subtle">
                    {{ getUnifiedDayLabel(day) }}
                  </UBadge>
                </div>
                <p class="text-sm text-muted">
                  {{ day.entries.length }} {{ day.entries.length === 1 ? 'plan activo' : 'planes activos' }} en esta vuelta
                </p>
              </div>

              <div
                v-if="countCompletedEntries(day) === day.entries.length"
                class="inline-flex items-center gap-2 text-sm font-medium text-primary"
              >
                <UIcon name="i-lucide-check" class="size-4" />
                <span>Completado</span>
              </div>
              <p v-else class="text-sm text-muted">
                {{ countCompletedEntries(day) }} de {{ day.entries.length }} tarjetas listas
              </p>
            </button>

            <div v-if="isUnifiedDayOpen(day.selectionIndex)" class="space-y-4 p-5">
              <div class="grid gap-4 lg:grid-cols-3">
                <div
                  v-for="entry in day.entries"
                  :key="`${entry.row.key}-${entry.slot.selectionIndex}`"
                  class="space-y-3"
                >
                  <div class="flex flex-wrap items-center gap-2">
                    <UBadge color="primary" variant="subtle">
                      {{ entry.plan.nombre }}
                    </UBadge>
                    <UBadge color="neutral" variant="subtle">
                      {{ formatPlanType(entry.plan.tipo) }}
                    </UBadge>
                  </div>

                  <AdminMenuSlotEditor
                    v-model="entry.slot.slot"
                    :title="entry.plan.nombre"
                    :catalog-items="catalogItems"
                    :main-types="entry.plan.tipo === 'DESAYUNO' ? ['desayuno'] : ['comida', 'cena']"
                    :side-types="['guarnicion']"
                    :additional-types="['guarnicion', 'ramekin']"
                    :loading="isEditorLoading"
                    :main-error="getPlanSlotError(entry.rowIndex, entry.slot.selectionIndex, 'platilloPrincipal')"
                    :container-error="getPlanSlotError(entry.rowIndex, entry.slot.selectionIndex, 'contenedor')"
                  />
                </div>
              </div>
            </div>
          </section>
        </div>
      </div>
    </UCard>

    <UCard :ui="sectionCardUi">
      <div class="space-y-2">
        <p class="text-xs font-semibold uppercase tracking-[0.18em] text-primary/80">
          Construcción del pedido
        </p>
        <h2 class="text-xl font-semibold text-primary">
          Planes y cantidades
        </h2>
        <p class="text-sm leading-6 text-muted">
          Elige uno o varios planes y después ajusta la cantidad de cada uno dentro del mismo pedido.
        </p>
      </div>

      <UFormField
        name="planItems"
        label="Planes del pedido"
        description="Puedes seleccionar varios planes; el editor del menú sólo activará los tiempos que correspondan."
        :ui="fieldUi"
      >
        <USelectMenu
          :model-value="selectedPlanIds"
          :items="planSelectionOptions"
          label-key="label"
          value-key="value"
          class="w-full"
          multiple
          placeholder="Selecciona uno o más planes"
          :search-input="{ placeholder: 'Buscar planes...' }"
          @update:model-value="handlePlanSelectionChange"
        />
      </UFormField>

      <div class="space-y-4">
        <div
          v-for="(planItem, index) in state.planItems"
          :key="planItem.key"
          class="rounded-2xl border border-default/60 bg-default/25 p-4 sm:p-5"
        >
          <div class="mb-4 flex flex-wrap items-center justify-between gap-3">
            <div class="flex flex-wrap items-center gap-2">
              <UBadge color="primary" variant="subtle">
                {{ plansById.get(planItem.planId)?.nombre || 'Plan' }}
              </UBadge>
              <UBadge v-if="plansById.get(planItem.planId)" color="neutral" variant="subtle">
                {{ formatPlanType(plansById.get(planItem.planId)!.tipo) }}
              </UBadge>
            </div>

            <UButton
              color="error"
              variant="ghost"
              icon="i-lucide-trash-2"
              class="cursor-pointer"
              @click="removePlanRow(index)"
            />
          </div>

          <div class="grid gap-4 xl:grid-cols-[minmax(0,0.55fr)_minmax(0,1fr)]">
            <UFormField
              :name="`planItems.${index}.quantity`"
              label="Cantidad"
              description="Número de paquetes."
              :ui="fieldUi"
            >
              <UInputNumber
                :model-value="planItem.quantity ?? undefined"
                class="w-full"
                size="xl"
                orientation="vertical"
                :min="1"
                :step="1"
                placeholder="1"
                @update:model-value="(value) => handleQuantityChange(planItem, value)"
              />
            </UFormField>

            <UFormField
              :name="`planItems.${index}.notas`"
              label="Notas por plan"
              description="Opcional para personalizaciones o contexto."
              :ui="fieldUi"
            >
              <UInput
                v-model="planItem.notas"
                class="w-full"
                size="xl"
                placeholder="Sin cebolla, empaque extra, etc."
              />
            </UFormField>
          </div>

          <div
            v-if="planItem.planId && plansById.get(planItem.planId)"
            class="mt-4 rounded-2xl border border-default/60 bg-elevated/40 p-4"
          >
            <div class="flex flex-wrap items-center gap-2">
              <UBadge color="primary" variant="subtle">
                {{ formatPlanType(plansById.get(planItem.planId)!.tipo) }}
              </UBadge>
              <UBadge color="neutral" variant="subtle">
                {{ plansById.get(planItem.planId)!.dishCount }} platillos base
              </UBadge>
              <UBadge :color="plansById.get(planItem.planId)!.isActive ? 'success' : 'warning'" variant="subtle">
                {{ plansById.get(planItem.planId)!.isActive ? 'Activo' : 'Inactivo' }}
              </UBadge>
              <UBadge
                v-if="planItem.slots.length"
                :color="rowHasManualSlotEdits(planItem) ? 'warning' : 'success'"
                variant="subtle"
              >
                {{ planItem.slots.length }} días cargados
              </UBadge>
            </div>
            <p class="mt-3 text-sm text-muted">
              {{ formatCurrency((plansById.get(planItem.planId)!.precio ?? 0) * Number(planItem.quantity ?? 0)) }}
              · {{ plansById.get(planItem.planId)!.dishCount * Number(planItem.quantity ?? 0) }} platillos solicitados
            </p>
            <p
              v-if="selectedMenuDetail && rowHasManualSlotEdits(planItem)"
              class="mt-2 text-xs text-muted"
            >
              Este plan ya tiene ajustes manuales. Si cambias menú, plan o cantidad te pediremos confirmar antes de regenerarlo.
            </p>
          </div>
        </div>
      </div>

      <UAlert
        v-if="!filledPlanRows.length"
        title="Aún no hay planes capturados"
        description="Agrega al menos un plan con cantidad para poder guardar el pedido."
        color="neutral"
        variant="soft"
        icon="i-lucide-package-open"
      />
    </UCard>

    <UCard :ui="sectionCardUi">
      <div class="space-y-2">
        <p class="text-xs font-semibold uppercase tracking-[0.18em] text-primary/80">
          Totales y notas
        </p>
        <h2 class="text-xl font-semibold text-primary">
          Ajustes finales
        </h2>
        <p class="text-sm leading-6 text-muted">
          Cierra el pedido con descuentos, extras, costos de entrega y notas para el equipo.
        </p>
      </div>

      <div class="grid gap-4 xl:grid-cols-[minmax(0,0.55fr)_repeat(3,minmax(0,0.7fr))]">
        <UFormField
          name="currency"
          label="Moneda"
          description="Usa MXN salvo casos especiales."
          :ui="fieldUi"
        >
          <UInput
            v-model="state.currency"
            class="w-full"
            size="xl"
            maxlength="3"
            placeholder="MXN"
          />
        </UFormField>

        <UFormField
          name="descuento"
          label="Descuento"
          description="Monto a restar del subtotal."
          :ui="fieldUi"
        >
          <UInputNumber
            :model-value="state.descuento ?? undefined"
            class="w-full"
            size="xl"
            orientation="vertical"
            :min="0"
            :step="10"
            placeholder="0"
            @update:model-value="(value) => state.descuento = value === undefined ? null : Number(value)"
          />
        </UFormField>

        <UFormField
          name="extras"
          label="Extras"
          description="Ajustes positivos fuera del plan base."
          :ui="fieldUi"
        >
          <UInputNumber
            :model-value="state.extras ?? undefined"
            class="w-full"
            size="xl"
            orientation="vertical"
            :min="0"
            :step="10"
            placeholder="0"
            @update:model-value="(value) => state.extras = value === undefined ? null : Number(value)"
          />
        </UFormField>

        <UFormField
          name="costoEnvio"
          label="Costo de envío"
          description="Cargo logístico del pedido."
          :ui="fieldUi"
        >
          <UInputNumber
            :model-value="state.costoEnvio ?? undefined"
            class="w-full"
            size="xl"
            orientation="vertical"
            :min="0"
            :step="10"
            placeholder="0"
            @update:model-value="(value) => state.costoEnvio = value === undefined ? null : Number(value)"
          />
        </UFormField>
      </div>

      <div class="grid gap-4 xl:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
        <UFormField
          name="tagsText"
          label="Tags"
          description="Sepáralos por coma para filtrar después."
          :ui="fieldUi"
        >
          <UInput
            v-model="state.tagsText"
            class="w-full"
            size="xl"
            placeholder="urgente, oficina, corte-viernes"
          />
        </UFormField>

        <div class="rounded-2xl border border-default/60 bg-default/25 p-4 sm:p-5">
          <p class="text-xs font-semibold uppercase tracking-[0.16em] text-muted">
            Resumen del pedido
          </p>

          <div class="mt-4 grid gap-3 sm:grid-cols-2">
            <div class="rounded-2xl border border-default/60 bg-elevated/40 p-4">
              <p class="text-xs uppercase tracking-[0.16em] text-muted">
                Subtotal
              </p>
              <p class="mt-2 text-lg font-semibold text-highlighted">
                {{ formatCurrency(subtotalPreview, state.currency || 'MXN') }}
              </p>
            </div>

            <div class="rounded-2xl border border-default/60 bg-elevated/40 p-4">
              <p class="text-xs uppercase tracking-[0.16em] text-muted">
                Total estimado
              </p>
              <p class="mt-2 text-lg font-semibold text-highlighted">
                {{ formatCurrency(totalPreview, state.currency || 'MXN') }}
              </p>
            </div>

            <div class="rounded-2xl border border-default/60 bg-elevated/40 p-4">
              <p class="text-xs uppercase tracking-[0.16em] text-muted">
                Platillos solicitados
              </p>
              <p class="mt-2 text-lg font-semibold text-highlighted">
                {{ requestedDishCountPreview }}
              </p>
            </div>

            <div class="rounded-2xl border border-default/60 bg-elevated/40 p-4">
              <p class="text-xs uppercase tracking-[0.16em] text-muted">
                Paquetes / bolsas
              </p>
              <p class="mt-2 text-lg font-semibold text-highlighted">
                {{ bagCountPreview }}
              </p>
            </div>
          </div>

          <div class="mt-4 rounded-2xl border border-default/60 bg-default/70 p-4 text-sm text-muted">
            <p v-if="selectedMenuDetail">
              Al guardar se tomarán snapshots exactos del menú <span class="font-medium text-highlighted">{{ selectedMenuDetail.name }}</span>
              con la selección final editada dentro del pedido.
            </p>
            <p v-else>
              Si guardas sin menú vinculado, el pedido quedará creado pero con la resolución de platillos pendiente.
            </p>
          </div>
        </div>
      </div>

      <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <UFormField
          name="notas"
          label="Notas visibles"
          description="Comentarios útiles para atención o entrega."
          :ui="fieldUi"
        >
          <UTextarea
            v-model="state.notas"
            class="w-full"
            :rows="4"
            autoresize
            placeholder="Comentarios generales del cliente o del pedido"
          />
        </UFormField>

        <UFormField
          name="notasInternas"
          label="Notas internas"
          description="Sólo para operación y control administrativo."
          :ui="fieldUi"
        >
          <UTextarea
            v-model="state.notasInternas"
            class="w-full"
            :rows="4"
            autoresize
            placeholder="Instrucciones para cocina, empaque, ruta o cobranza"
          />
        </UFormField>
      </div>
    </UCard>

    <div
      v-if="!hideSubmit"
      class="flex flex-col gap-3 rounded-[24px] border border-default/70 bg-elevated/30 p-4 sm:flex-row sm:items-center sm:justify-between"
    >
      <div class="space-y-1">
        <p class="text-sm font-medium text-highlighted">
          {{ filledPlanRows.length }} {{ filledPlanRows.length === 1 ? 'plan cargado' : 'planes cargados' }}
        </p>
        <p class="text-sm text-muted">
          Total estimado: {{ formatCurrency(totalPreview, state.currency || 'MXN') }}
        </p>
      </div>

      <UButton
        type="submit"
        :disabled="!canSubmit"
        :loading="isSubmitting"
        icon="i-lucide-save"
        class="cursor-pointer sm:w-auto"
      >
        Crear pedido
      </UButton>
    </div>

    <UModal
      v-model:open="regenerationConfirmOpen"
      :title="confirmRegenerationTitle"
      :description="confirmRegenerationDescription"
    >
      <template #body>
        <div class="space-y-4">
          <UAlert
            color="warning"
            variant="soft"
            icon="i-lucide-triangle-alert"
            title="Se perderán los ajustes manuales"
            description="Los slots volverán a llenarse desde el menú semanal actual y se reemplazará la edición hecha a mano."
          />
        </div>
      </template>

      <template #footer>
        <div class="flex w-full justify-end gap-3">
          <UButton
            color="neutral"
            variant="ghost"
            @click="cancelRegeneration"
          >
            Cancelar
          </UButton>
          <UButton
            color="warning"
            icon="i-lucide-refresh-cw"
            @click="confirmRegeneration"
          >
            Regenerar
          </UButton>
        </div>
      </template>
    </UModal>
  </UForm>
</template>
