// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/vue'

import _admin_menu_index from './admin-menu-index.bones.json'
import _admin_menu_create_slots from './admin-menu-create-slots.bones.json'
import _admin_menu_edit_fields from './admin-menu-edit-fields.bones.json'
import _admin_menu_edit_slots from './admin-menu-edit-slots.bones.json'
import _admin_food_catalog_edit_fields from './admin-food-catalog-edit-fields.bones.json'
import _admin_food_catalog_edit_sidebar from './admin-food-catalog-edit-sidebar.bones.json'

configureBoneyard({"color":"#e4e4e7","darkColor":"#27272a","animate":"shimmer"})

registerBones({
  "admin-menu-index": _admin_menu_index,
  "admin-menu-create-slots": _admin_menu_create_slots,
  "admin-menu-edit-fields": _admin_menu_edit_fields,
  "admin-menu-edit-slots": _admin_menu_edit_slots,
  "admin-food-catalog-edit-fields": _admin_food_catalog_edit_fields,
  "admin-food-catalog-edit-sidebar": _admin_food_catalog_edit_sidebar,
})
